### PR TITLE
Dummy improvements

### PR DESCRIPTION
**Pull request by warden161**
I don't know why that csproj modification exists

**TODO**
- [ ] Movement controls
- [x] Scp173Dummy
- [x] Scp049Dummy
- [x] Scp939Dummy
- [x] Scp0492Dummy
- [x] Scp106Dummy
- [x] Scp096Dummy

i literally have no clue if this will actually work or need a patch or something

### CODE REVIEW

**Comment by warden161** [comment]
ok i forgot to work from main branch instead of my dev branch oopsie

**Comment by warden161** [comment]
I have no clue how to make vs stop touching the csproj.

**Comment by warden161** [comment]
We do a little committing
idk about making humandummy, i think basedummy should work fine for that
movement tomorrow
will finish all scps rn

**Comment by warden161** [comment]
Forgot about 049-2 dummy.

**Comment by warden161** [comment]
Should be good for all SCPs. Need to add position, rotation and movement now.
EDIT: Will do tomorrow. Very tired.

**Comment by warden161** [comment]
If someone feels like adding an 079 dummy feel free to do so.

**Comment by warden161** [comment]
I'm aware of a problem with how I did this. I will fix it ASAP.

**Comment by xRoier** [comment]
> If someone feels like adding an 079 dummy feel free to do so.

How do you even do that 💀

**Review by Jesus-QC — COMMENTED** [review]
This seems like a denied pr

**Comment by Jesus-QC** [comment]
Well, lmk when you are finished

**Comment by warden161** [comment]
this doesnt even work anyway, i cant be assed to fix it

**Pull request closed without merging**
